name: meson sanitizer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libutmpld
    steps:
    - name: Install libsystemd-dev
      run: sudo apt-get install libsystemd-dev
    - uses: actions/checkout@v3
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        directory: build
        setup-options: -Db_sanitize=address,undefined
        options: --verbose
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: build
        setup-options: -Db_sanitize=address,undefined
        options: --verbose
