name: meson build & test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install pam-devel
      run: sudo apt-get install libpam0g-dev
    - uses: actions/checkout@v3
    - name: Switch libutmpld directory
      run: cd libutmpld
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        options: --verbose
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        options: --verbose
